
CREATE TABLE IF NOT EXISTS shows (
    id SERIAL PRIMARY KEY,
    movie_name VARCHAR(100) NOT NULL,
    running_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS seat_reservations (
    id SERIAL PRIMARY KEY,
    shows_id SERIAL NOT NULL,
    seat INT NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    UNIQUE (shows_id, seat),
    FOREIGN KEY (shows_id) REFERENCES shows(id) ON DELETE CASCADE
);

